version: "3.8"
services:
  nginx:
    build: ./nginx/.
    ports:
      - "8080:80"
    links:
      - net
      - java
      - node

  net:
    image: lnicho/ow-my-aws-is-broken:ex-1-net
    links:
      - postgres

  java:
    image: lnicho/ow-my-aws-is-broken:ex-2-java
    depends_on:
      - "postgres"
    links:
      - postgres

  node:
    image: lnicho/ow-my-aws-is-broken:ex-1-node
    links:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=demouser
      - POSTGRES_PASSWORD=demopassword
