version: "3.8"
services:
  nginx:
    build: ./nginx/.
    ports:
      - "8080:80"
    links:
      - net
      - java
      - node

  net:
    image: lnicho/ow-my-aws-is-broken:ex-2-net

  java:
    image: lnicho/ow-my-aws-is-broken:ex-2-java

  node:
    image: lnicho/ow-my-aws-is-broken:ex-2-node
